### ISSUE TITLE
Project stopped building with versions 1.0.10, 1.0.9

### ISSUE THREAD

**Issue by aroslov** [BCJTI/ng2-cookies#42]
Stack trace:

```
Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 49:22 in the original .ts file), resolving symbol Cookie in node_modules/ng2-cookies/cookie.d.ts

at positionalError (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:25730:39)
    at simplifyInContext (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:25567:31)
    at StaticReflector.simplify (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:25581:17)
    at StaticReflector.annotations (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:25077:64)
    at NgModuleResolver.resolve (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:17557:86)
    at CompileMetadataResolver.getNgModuleMetadata (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:18058:64)
    at addNgModule (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:24839:62)
    at ./node_modules/@angular/compiler/bundles/compiler.umd.js:24850:18
    at Array.forEach (native)
    at _createNgModules (/opt/atlassian/pipelines/agent/build/node_modules/@angular/compiler/bundles/compiler.umd.js:24849:30)
Compilation failed
```

Seems like the breaking change was introduced after ng2-cookies@1.0.8

**Comment by Bigous** [comment]
I think #43 fix this one.

**Comment by carcamano** [comment]
@aroslov please uptade your version and try again!
