### ISSUE TITLE
Publish a new version to npm

### ISSUE THREAD

**Issue by denissb** [BCJTI/ng2-cookies#63]
The current version on npm is outdated and causes some problems with the latest build systems (webpack 3+), can we publish a new version with the latest changes?

**Comment by carcamano** [comment]
Hi Denis.

Can you send me a PR with required changes?

Thanks

**Comment by denissb** [comment]
Sorry, my bad had incorrect version in `package-lock.json`. Closing.

**Comment by denissb** [comment]
No, the porblem is still there when building with @angular/cli, I get:
`LicenseWebpackPlugin✖ ｢wdm｣: TypeError: licenseType.indexOf is not a function
    at LicenseTextReader.readLicense (/Users/id844903/proximus/web/magnolia-angular-usage-ng/node_modules/@angular-devkit/build-angular/node_modules/license-webpack-plugin/dist/LicenseTextReader.js:29:40)
    at PluginChunkReadHandler.processModule (/Users/id844903/proximus/web/magnolia-angular-usage-ng/node_modules/@angular-devkit/build-angular/node_modules/license-webpack-plugin/dist/PluginChunkReadHandler.js:52:62)`

There is not code change required for this as I see in package.json the version is specified as a string (is an object in 1.0.12 on npm, which is deprecated). I think you just need to publish a new one with the changes since Apr 26, 2017. I am not the owner of the package so I can't do it :(
